major bugfixes

diff --git a/x2ogg b/x2ogg
--- a/x2ogg
+++ b/x2ogg
@@ -3,6 +3,9 @@ rate=$1   # average bitrate (VBR)
 indir=$2  # source directory
 outdir=$3 # destination directory
 
+indir=`echo $indir | sed "s/\/$//g"`
+outdir=`echo $outdir | sed "s/\/$//g"`
+
 supported="mp3 flac" # list of supported input types
 ext="ogg"
 
@@ -12,16 +15,16 @@ ext="ogg"
 
 printerr ()
 {
-  echo >&2 "ABORTING: $1";
-  exit 1;
+  echo >&2 "ABORTING: $1"
+  exit 1
 }
 
 test_exist ()
 {
   # look in $1 for files that end with .$2
   # succeed if any matches were found
-  files=`find "$1" -type f -iname "*.$2" | wc -l`
-  return `test "$files" != "0"`
+  files=$(find "$1" -type f -iname "*.$2" | wc -l)
+  return $(test "$files" != "0")
 }
 
 ####################
@@ -34,22 +37,24 @@ test -d "$indir" || printerr "input directory not found: \"$indir\""
 # verify existence of supported input files
 found=0
 for ext_i in $supported; do
-  test_exist "$indir" "$ext_i" &&
-  {
-    (( found++ ));
-    echo "found $ext_i";
-  }
+  if test_exist "$indir" "$ext_i"; then
+    let found+=1
+    echo "found $ext_i"
+
+    # check specific dependencies
+    case $ext_i in
+      mp3|MP3) if   hash mpg321; then mpg="mpg321"
+               elif hash mpg123; then mpg="mpg123"
+               else printerr "mpg321 or mpg123 requred."
+               fi
+      ;;
+    esac
+  fi
 done
 test $found -eq 0 && printerr "no supported input types found."
 
-# check dependencies
+# check universal dependencies
 hash oggenc 2>&- || printerr "oggenc requred."
-test_exist "$indir" "mp3" &&
-{
-  {hash mpg321 2>&- && mpg="mpg321"} ||
-  {hash mpg123 2>&- && mpg="mpg123"} ||
-    printerr "mpg321 or mpg123 requred."
-}
 
 # make sure the output file exists
 test -d "$outdir" || mkdir "$outdir"
@@ -61,12 +66,16 @@ test -d "$outdir" || printerr "output directory could not be created."
 
 # PROCEDURE: mp3
 for input in "$indir"/*.{mp3,MP3}; do
-  output="$outdir"/${input%.*}.$ext
+  test -f "$input" || continue
+  output="$outdir"/`basename "${input%.*}"`.$ext
   $mpg "$input" -w - | oggenc - -b $rate -o "$output"
+  if [ $? -eq 130 ]; then echo "CTRL+C pressed"; exit 130; fi
 done
 
 # PROCEDURE: flac
 for input in "$indir"/*.{flac,FLAC}; do
-  output="$outdir"/${input%.*}.$ext
+  test -f "$input" || continue
+  output="$outdir"/`basename "${input%.*}"`.$ext
   oggenc "$input" -b $rate -o "$output"
+  if [ $? -eq 130 ]; then echo "CTRL+C pressed"; exit 130; fi
 done
